### ISSUE TITLE
MyBatis migration not compiling procedures

### ISSUE THREAD

**Issue by jmodi1982** [mybatis/migrations#46]
hi,

we are using MyBatis for applying DB changes and in 1 of the script there was a procedure which we were creating. MyBatis removed the comments while performing migraitons and that lead to procedure not compiling successfully. However Mybatis migraiton did not fail the execution but it provided Success status.

When we went to Database to check the procedure, it was broken.

Please can you confirm if MyBatis migrations can be used to Create/Replace Procedures,Functions, Packages in Oracle database.

Thanks

**Comment by harawata** [comment]
Please provide sample scripts to reproduce the problem.

**Comment by jmodi1982** [comment]
All the comments from the below script gets removed, I don't want the comments inside stored procedure to be removed. Please find below a sample script - 

--*****************************************************************************
--Request                       : 1548
--Date                          : 26/04/2016
--Onsite Anchor                 : John March
--******************************************************************************/

CREATE OR REPLACE PROCEDURE CheckPassword
 --**********************************************************************
 -- TYPE               : Procedure
 -- Orginal Procedure  : inet_pwrup_qgpn_price
 -- NAME               : DP_inet_pwrup_qgpn_price
 -- INPUT Parameters   : None
 -- PURPOSE            :This procedure is used to populate the quasi generic
                         part price and other details
 -- ------ ---------- ---   ---------------------------------------------
    @username VARCHAR(20),
    @password varchar(20)
AS
BEGIN

SET NOCOUNT ON

IF EXISTS(SELECT * FROM usertable WHERE username = @username AND password = @password)
    SELECT 'true' AS UserExists
ELSE
    SELECT 'false' AS UserExists

END

**Comment by harawata** [comment]
I couldn't create that procedure even in PL/SQL.
The below script worked on Oracle 11g (ojdbc7 driver version 12.1.0.2).

```sql
-- // First migration.
-- Migration SQL that makes the change goes here.

-- @DELIMITER |
CREATE OR REPLACE PROCEDURE myproc IS
/*
Comments
Comments
Comments
*/
BEGIN
	INSERT INTO person (id, name1) VALUES (999, 'John');
END;
|
-- @DELIMITER ;

-- See if the procedure has an error.
SELECT * FROM SYS.USER_ERRORS WHERE name='MYPROC' AND type='PROCEDURE';

-- //@UNDO
-- SQL to undo the change goes here.

DROP PROCEDURE myproc;
```

Some comments:

- Even when the procedure has compile error, Oracle driver creates the procedure and throws no exception. So, to Migrations, it's still SUCCESS.  
In the above script, I added a SELECT statement to check the error. It might be better than nothing.
- To leave comments in procedure, you have to use multi-line format ```/* .... */```.
- The ```@DELIMITER``` syntax requires MyBatis 3.3.0 or later.

Here is the environment properties:

```ini
time_zone=GMT+0:00

driver=oracle.jdbc.driver.OracleDriver
url=jdbc:oracle:thin:@192.168.57.101:1521:ORCL
username=xxx
password=xxx

send_full_script=false
delimiter=;
full_line_delimiter=false
auto_commit=false
changelog=CHANGELOG
```

I close this issue because creating procedure works :-)

**Comment by jmodi1982** [comment]
Thanks for the info, we also changed source code to use ## instead of -- as script comments as SQL. Everything looks good for now, will keep you posted if i come across any new issues

**Comment by harawata** [comment]
Good to know that ```##``` works, too.
Thanks for the update!

**Comment by jmodi1982** [comment]
Hi,

I see a big issue and I need some immediate  remediation  based on your  experience.  

Even when the procedure has compile error, Oracle driver creates the procedure and throws no exception. So, to Migrations, it's still SUCCESS. Due to this the changelog table is updated and I cannot run the script again. So I have to create another script with correct procedure code and then again rerun it. Is there a way, using user_errors table we can fail the script so that the Changelog table is not updated with success. The developer can then go back correct the procedure code and rerun the same script file via mybatis. I agree the stored procedure however would be errored stored procedure, but I want to avoid creating new files for every error in my pl/sql codes.

Looking forward for your guidance on this issue.

Thanks

**Comment by harawata** [comment]
Hi,

After the incorrectly succeeded 'up' command, you just need to execute the 'down' command.
Of course, you need to write ```DROP PROCEDURE``` in the 'UNDO' part (see my sample script above).
The 'down' command will remove the row from the changelog table as well.

I had expected that Oracle has some kind of configuration option for this behavior, but couldn't find it.
There seems to be some [trick](http://stackoverflow.com/questions/16429069/can-i-make-sqlplus-exit-with-an-error-on-function-compilation-failure) to achieve this in SQL*Plus, but it wouldn't work with JDBC (even if it did, I wouldn't recommend it).

Hope this helps,
Iwao

**Comment by jmodi1982** [comment]
Hi,

Please do let us know if you find any oracle configuration  which can solve this issue. At least we should get the compilation error and the script should be exited since we usually run a large no of scripts and a non-compiled procedure  could cause serious dB  inconsistencycle

Also DBAY don't like the idea of going to sql+ to see if the stored procedure has thrown any compilation  errors. They want to see it automatically  after  procedure  is updated  and exit the script if there is ano error.

Thanks.

**Comment by harawata** [comment]
I totally understand what you and your team want. Strange implementation indeed :confused:

Anyway, I think I have found a solution to this problem.
I will open a new issue and let you know.

**Comment by harawata** [comment]
Well, I should just reopen this one.

**Comment by harawata** [comment]
OK, I have fixed it.
```migrate up``` command should now fail if the procedure has a compile error.

To try it, just clone this repository and execute ```mvn clean package```.
The .zip bundle will be generated in the target directory.
Please let me know if it works.

Thank you!
Iwao

**Comment by jmodi1982** [comment]
Will it print the compilation error as well ?

**Comment by harawata** [comment]
I don't think so. The only message I see in the warning is that the statement execution completed with an error.

**Comment by jmodi1982** [comment]
Is there any configuration or code by which we can enable the error message as well?

**Comment by jmodi1982** [comment]
Hi,

Is it possible to provide the error message from show errors table ?

Thanks,
Jeemish

**Comment by harawata** [comment]
How about this?

You create a special script file 'onabort.sql' in the scripts directory.
The content would look as follows.

```sql
-- Reset delimiter in case creating procedure was aborted
// @DELIMITER ;
-- Output error. As this is a global file, you cannot specify the procedure name.
SELECT * FROM SYS.USER_ERRORS WHERE type='PROCEDURE';
```

Whenever ```migration up``` is aborted by SQLException, Migrations executes this script (only if it exists, of course).

For example, here is the result of ```migrate up``` if I removed the semicolon at the end of the INSERT statement of the above script.

```
------------------------------------------------------------------------
-- MyBatis Migrations - up
------------------------------------------------------------------------
========== Applying: 20160506152242_first_migration.sql ========================
--  First migration.
-- Migration SQL that makes the change goes here.
CREATE OR REPLACE PROCEDURE myproc IS
/*
Comments
Comments
Comments
*/
BEGIN
        INSERT INTO person (id, name1) VALUES (999, 'John')
END;


Error executing: CREATE OR REPLACE PROCEDURE myproc IS
/*
Comments
Comments
Comments
*/
BEGIN
        INSERT INTO person (id, name1) VALUES (999, 'John')
END;

.  Cause: java.sql.SQLWarning: Warning: execution completed with warning

========== Executing onabort.sql script. =======================================
-- reset delimiter in case creating procedure was aborted.
SELECT * FROM SYS.USER_ERRORS WHERE type='PROCEDURE'

NAME    TYPE    SEQUENCE        LINE    POSITION        TEXT    ATTRIBUTE       MESSAGE_NUMBER  
MYPROC  PROCEDURE       3       11      0       PLS-00103: Encountered the symbol "end-of-file" when expecting one of the following:

   ( begin case declare end exception exit for goto if loop mod
   null pragma raise return select update while with
   <an identifier> <a double-quoted delimited-identifier>
   <a bind variable> << continue close current delete fetch lock
   insert open rollback savepoint set sql execute commit forall
   merge pipe purge
        ERROR   103
MYPROC  PROCEDURE       2       8       2       PL/SQL: SQL Statement ignored   ERROR   0
MYPROC  PROCEDURE       1       8       54      PL/SQL: ORA-00933: SQL command not properly ended       ERROR   0

------------------------------------------------------------------------
-- MyBatis Migrations FAILURE
-- Total time: 0s
-- Finished at: Thu May 12 23:43:12 JST 2016
-- Final Memory: 25M/479M
------------------------------------------------------------------------
```

Does this meet your requirement?

**Comment by jmodi1982** [comment]
Yes, this would meet our requirements, however we would have the SQL command to show errors for Procedure, Functions, Packages, Triggers as well. That should work isn't it ?

Is this change already implemented in the source code ?

Thanks,
Jeemish

**Comment by jmodi1982** [comment]
Just wanted to confirm MyBatis command will fail and throw a similar warning if there is a compilation error in Functions, Packages, Triggers as well.

**Comment by harawata** [comment]
> Just wanted to confirm MyBatis command will fail and throw a similar warning if there is a compilation error in Functions, Packages, Triggers as well.

I would expect so. You should be able to verify this behavior with the current snapshot if you want to be 100% sure.

I need to clean up the code a little bit before pushing the change.

**Comment by harawata** [comment]
@jmodi1982 The onabort.sql script should work with the latest 3.3.0-SNAPSHOT.

**Comment by svscorp** [comment]
@harawata latest snapshot doesn't start (compiled, but errors out on run).

"could not find or load main class org.apache.ibatis.migration.Migrator".

Same issue (as the topic) exists with creating triggers - trying to get a working version of 3.3.0-snapshot (do you have one for download?).

**Comment by harawata** [comment]
Hi @jmodi1982 ,

In 3.3.2, a new per-environment option `ignore_warnings` is added and its default value is `true`.
So, by default, warnings do not stop migrations.
For your use case, you may have to add `ignore_warnings=false` to your environment properties files.

We've got several reports about migration being aborted by warnings unexpectedly and decided to change the default behavior.
I apologize for the confusing move and hope you support our decision.

Thank you!
